### ISSUE TITLE
Release 1.2.8

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtmros_common#595]
If anyone wants to hold please respond.
Many changes since 1.2.6 made in early October.

**Comment by k-okada** [comment]
since https://github.com/start-jsk/rtmros_common/pull/602 has passed, I think we are ready to release? or it is dangerous to release because they are going to sync dep package very soon?

anyway to confirm https://github.com/start-jsk/rtmros_common/issues/629 I'll release only for indigo, since as far as I know, I'm only indigo user so it does not have any problem.

**Comment by 130s** [comment]
> since #602 has passed, I think we are ready to release? or it is dangerous to release because they are going to sync dep package very soon?

+1 to wait until the next sync (the one after the upcoming sync) for Hydro.

**Comment by 130s** [comment]
Changed title from 1.2.7 (already exists) to 1.2.8. 
Is it a good time for the release?

**Comment by k-okada** [comment]
they are preparing hydro sync soon, so better to wait for a few days, I
also want switch to use {openrtm,openhrp3,hrpsys}-release , instead of
rosbuiild packages as we did in euslisp,
https://github.com/jsk-ros-pkg/jsk_roseus/blob/master/setup.sh

--
◉ Kei Okada

**Comment by 130s** [comment]
I see. [Now that Hydro sync is done](http://lists.ros.org/pipermail/ros-users/2015-February/069166.html) I'll appreciate once everything is set up ping me or you can make a new release.

**Comment by k-okada** [comment]
can we release openrtm/openhrp3/hrpsys, which we no longer used rospackage
in start-jsk, but directly release from tork-a/*-release repo,
these new package is no longer pactkin package, which is cmake package (
https://github.com/tork-a/hrpsys-release/blob/release/indigo/hrpsys/package.xml#L57)
but still we copy package.xml to share/package.xml so that we can find via
`rospack find`and enable launch file to use them (
https://github.com/tork-a/hrpsys-release/blob/release/indigo/hrpsys/CMakeLists.txt#L177
)

- now we consider /opt/ros/hydro as --prefix, so they install everything
under that repository create  symbolic link to use some files under ros
package prefix (/opt/ros/hydro/share/<package>'
- it works ok if you use deb version
- if you use source code and use `catkin build` , the problem is new catkin
tools did not set ROS_PACKAGE_PATH to cmake packages, is you use
catkin_make_isolated, it should be ok

se  https://github.com/jsk-ros-pkg/jsk_common/pull/745

--
◉ Kei Okada

**Comment by 130s** [comment]
I'm afraid I'm not good enough to answer to all the regards.

> can we release openrtm/openhrp3/hrpsys, (skip) but still we copy package.xml to share/package.xml

That sounds like a totally valid [ROS 3rd party package](http://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty#Releasing_a_Third_Party_Package).

So, are we now ready to release `rtmros_common`?

**Comment by k-okada** [comment]
ok, I have switched to new release repo for hydro, once they passed compile
process, please release rtmros_common for both hydro/indigo
 https://github.com/ros/rosdistro/pulls?q=is%3Apr+is%3Aclosed+openrtm

--
◉ Kei Okada

**Comment by k-okada** [comment]
I think we should release 1.2.7 to hydro, it has been released on indigo and working fine

**Comment by 130s** [comment]
Ah I see, and it looks like [you did already it](https://github.com/ros/rosdistro/pull/7241). Now I'll make 1.2.8.

**Comment by 130s** [comment]
On second thought we hold new release until we confirm the upstream issues are gone ([this](https://github.com/start-jsk/openhrp3/issues/57) for now).

**Comment by k-okada** [comment]
I think we'd better to fix https://github.com/start-jsk/rtmros_hironx/pull/325 (that should be done in hrpsys) and fix bronken qnx compile (https://github.com/fkanehiro/hrpsys-base/pull/494) and broken deb genertion(https://github.com/fkanehiro/hrpsys-base/pull/486/files) and release new hrpsys, and then release rtmros_common

**Comment by k-okada** [comment]
released new version as hrpsys released new version https://github.com/fkanehiro/hrpsys-base/pull/503
